<a href="https://colab.research.google.com/github/LivioXie/ICSI435_Group/blob/main/Solve_Puzzle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
mport numpy as num
import random
list1 = [0,1,2,3,4,5,6,7,8]
#Generating puzzle using 0 as the hole.
G1_matrix = num.zeros((3, 3))
#randomly assign numbers in 3 by 3 matrix
for i in range(3):#number of iterations
  for j in range(3):
      G1_matrix[i, j] = random.choice(list1)
      #Remove the used numbers from the list to avoid overlaps.
      list1.remove(G1_matrix[i, j])
print(G1_matrix)

[[8. 7. 0.]
 [6. 1. 5.]
 [3. 4. 2.]]
